#!/usr/bin/env bash
# shellcheck source=/home/fcher/.bash_profile
export BASH_SILENCE_DEPRECATION_WARNING=1
SHELLENV_DIR="$HOME/.config/shellenv"
if [[ -d $SHELLENV_DIR ]]; then
  export SHELLENV_DIR
  source "$SHELLENV_DIR/xdg-vars.sh"
  source "$SHELLENV_DIR/xdg-ninja.sh"
  source "$SHELLENV_DIR/settings.sh"
else
  echo "$SHELLENV_DIR" not found
  exit 1
fi

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
else
  echo "~/.bashrc not found"
  exit 1
fi
