#!/usr/bin/env bash
# shellcheck source=/home/fcher/.bash_profile
export BASH_SILENCE_DEPRECATION_WARNING=1
# echo "hello there!"
export SHELLENV_DIR="$HOME/.config/shellenv"
source "$SHELLENV_DIR/xdg-vars.sh"
source "$SHELLENV_DIR/xdg-ninja.sh"
source "$SHELLENV_DIR/settings.sh"

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
