#!/usr/bin/env bash
# shellcheck source=/home/fcher/.bashrc

iatest=$(expr index "$-" i)
# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# eval sudo on double ESC?
#eval "$(direnv hook bash)"
if [[ $iatest -gt 0 ]]; then
  # Expand the history size
  export HISTFILE="$XDG_CACHE_HOME/bash/.bash_history"
  if [[ -f "$HISTFILE" ]]; then
    mkdir -p "$(dirname "$HISTFILE")"
    touch "$HISTFILE"
  fi
  export HISTFILESIZE=10000
  export HISTSIZE=500
  export HISTTIMEFORMAT="%F %T" # add timestamp to history
  export HISTCONTROL=erasedups:ignoredups:ignorespace
  shopt -s histappend
  PROMPT_COMMAND='history -a'
  alias reloadbash="exec bash --login"
  alias confbash="v ~/.bashrc"
  # source -- ~/.local/share/blesh/ble.sh
  # [[ -d /usr/share/blesh ]] && source /usr/share/blesh/ble.sh --noattach
  if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
    source /opt/local/etc/profile.d/bash_completion.sh
  fi
  bind "set bell-style visible"
  # Allow ctrl-S for history navigation (with ctrl-R)
  # [[ $- == *i* ]] && stty -ixon
  bind "set completion-ignore-case on"
  bind "set show-all-if-ambiguous On"

  shopt -s autocd

  if command -v starship >/dev/null 2>&1; then
    eval "$(starship init bash)"
  else
    PROMPT_COMMAND='PS1_CMD1=$(__git_ps1 " (%s)")'
    PS1='\[\e[92m\]\u@\h \[\e[94m\]\w\[\e[0m\]${PS1_CMD1} \\$ '
  fi
  if command -v zoxide >/dev/null 2>&1; then eval "$(zoxide init bash)"; fi
  for file in "$XDG_CONFIG_HOME/bash/completions/"*; do
    [[ -f "$file" ]] && source "$file"
  done
  if command -v fzf >/dev/null 2>&1; then
    if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.bash ]; then
      source "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.bash
    # else
    #   eval "$(fzf --bash)"
    fi
  fi
  if [ -f "$HOME"/.bashrc_local ]; then
    source "$HOME"/.bashrc_local
  fi
  # [[ ${BLE_VERSION-} ]] && ble-attach
fi

path_clean
