@forward-modifiers Shift Control Alt
[default]
[system=""]

#Control{PrintScreen}	>> repeat[AudioVolumeMute, 5]
# Control{ScrollLock}		>> repeat[AudioVolumeDown, 5]
# Control{Pause}			>> repeat[AudioVolumeUp, 5]

Shift{PrintScreen}	>> MediaPlayPause
Shift{ScrollLock}	>> MediaTrackPrevious
Shift{Pause}		>> MediaTrackNext

Control{Shift{PrintScreen}}	>>	MediaStop

Alt{PrintScreen}	>> PrintScreen
Alt{ScrollLock}		>> ScrollLock
Alt{Pause}			>> Pause

PrintScreen	>> AudioVolumeMute
ScrollLock	>> AudioVolumeDown
Pause		>> AudioVolumeUp

ShiftRight >> Escape
CapsLock >> Escape
Alt{CapsLock} >> CapsLock

NumLock >> NumLock
Alt{NumLock} >> NumLock
