return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "arduino",
      "c",
      "dockerfile",
      "java",
      "javadoc",
      "json",
      "latex",
      "lua",
      "luadoc",
      "make",
      "markdown",
      "markdown_inline",
      "powershell",
      "python",
      "regex",
      "tmux",
      "toml",
      "yaml",
      "ssh_config",
      "kitty",
      "bibtex",
      "asm",
      "zsh",
      "vhdl",
    },
  },
}
