auto_reload 0.1
# vim:fileencoding=utf-8:foldmethod=marker

clipboard_control write-clipboard write-primary read-clipboard read-primary

#: Mouse {{{

mouse_hide_wait 3.0
# url_color #0087bd
url_style curly
open_url_with default
# url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls yes
#: }}}

#: Window layout {{{
remember_window_size  no
initial_window_width  640
initial_window_height 400
remember_window_position no
#}}}
#: Tab bar {{{
tab_bar_style separator
tab_separator " | "
tab_powerline_style round
#: }}}

#: Advanced {{{

#shell /opt/local/bin/bash --login
# shell . --login
# close_on_child_death no
# remote_control_password
# allow_remote_control no

#: To get a list of available actions, run::

#:     kitten @ --help

allow_hyperlinks yes
shell_integration enabled
allow_cloning ask

#: }}}

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# BEGIN_KITTY_THEME
# Chalk
include current-theme.conf
# END_KITTY_THEME

include ${KITTY_OS}.conf
