# vim:fileencoding=utf-8:foldmethod=marker
#
#: Color scheme {{{
background_opacity 1
background_blur 32
# transparent_background_colors
dynamic_background_opacity yes
# background_tint 1

# foreground #dddddd
background #1e1e2e


#: }}}
#: OS specific tweaks {{{
macos_titlebar_color system
macos_option_as_alt left
macos_quit_when_last_window_closed yes
macos_traditional_fullscreen yes
#: }}}
