#!/usr/bin/env zsh
# shellcheck source=/home/fcher/.config/zsh/.zshrc
# zmodload zsh/zprof

# Set a custom prompt for debug output with microsecond timestamps
# export PS4=$'\11%D{%s%6.} %N:%i> '
# Redirect debug output to a log file
# exec 3>&2 2>/tmp/zsh_profile.$$.log
# setopt xtrace prompt_subst

# z4h source "$ZDOTDIR/xdg_vars.sh"
# z4h source "$ZDOTDIR/xdg-ninja.sh"

########################################################################################################################################
# Personal Zsh configuration file. It is strongly recommended to keep all
# shell customization and configuration (including exported environment
# variables such as PATH) in this file or in files sourced from it.

# Periodic auto-update on Zsh startup: 'ask' or 'no'.
# You can manually run `z4h update` to update everything.
zstyle ':z4h:' auto-update 'no'
# Ask whether to auto-update this often; has no effect if auto-update is 'no'.
zstyle ':z4h:' auto-update-days '28'
# Keyboard type: 'mac' or 'pc'.
# if [[ $OSTYPE == "darwin" ]]; then
#   zstyle ':z4h:bindkey' keyboard 'mac'
# else
zstyle ':z4h:bindkey' keyboard 'pc'
# fi

# Start tmux if not already in tmux.
#zstyle ':z4h:' start-tmux command tmux -u new-session -A -D
zstyle ':z4h:' start-tmux no
# Whether to move prompt to the bottom when zsh starts and on Ctrl+L.
zstyle ':z4h:' prompt-at-bottom 'yes'

# Mark up shell's output with semantic information.
zstyle ':z4h:' term-shell-integration 'yes'
zstyle ':z4h:' propagate-cwd yes

# Right-arrow key accepts one character ('partial-accept') from
# command autosuggestions or the whole thing ('accept')?
zstyle ':z4h:autosuggestions' forward-char 'accept'

# Recursively traverse directories when TAB-completing files.
zstyle ':z4h:fzf-complete' recurse-dirs 'yes'
zstyle ':z4h:fzf-complete' fzf-bindings tab:repeat
zstyle ':z4h:*' fzf-flags --color=hl:5,hl+:5

# Enable direnv to automatically source .envrc files.
zstyle ':z4h:direnv' enable 'yes'
# Show "loading" and "unloading" notifications from direnv.
zstyle ':z4h:direnv:success' notify 'yes'

# Enable ('yes') or disable ('no') automatic teleportation of z4h over
# SSH when connecting to these hosts.
zstyle ':z4h:ssh:*' enable 'no'
# zstyle ':z4h:ssh:octopi.local' enable 'yes'
# zstyle ':z4h:ssh:*' send-extra-files '$XDG_CONFIG_HOME/vim/vimrc'

# Clone additional Git repositories from GitHub.
#
# This doesn't do anything apart from cloning the repository and keeping it
# up-to-date. Cloned files can be used after `z4h init`. This is just an
# example. If you don't plan to use Oh My Zsh, delete this line.
omzdir="ohmyzsh/ohmyzsh"
z4h install $omzdir || return
z4h install MichaelAquilina/zsh-you-should-use || return

# Install or update core components (fzf, zsh-autosuggestions, etc.) and
# initialize Zsh. After this point console I/O is unavailable until Zsh
# is fully initialized. Everything that requires user interaction or can
# perform network I/O must be done above. Everything else is best done below.
z4h init || return
#autoload -U colors && colors
# Extend PATH.

typeset -U PATH path
[[ -v SHELLENV_DIR ]] && source "$SHELLENV_DIR/settings.sh"

# Export environment variables.
fpath=($ZDOTDIR/completions $fpath)
HISTFILE="$ZDOTDIR/.histfile"
HISTSIZE=10000
SAVEHIST=10000

# Source additional local files if they exist.
# Use additional Git repositories pulled in with `z4h install`.

export omzplug=$omzdir/plugins
# z4h load $omzplug/colored-man-pages
z4h load $omzplug/sudo
z4h load MichaelAquilina/zsh-you-should-use

if command -v zoxide &>/dev/null; then eval "$(zoxide init zsh)"; fi
# eval "$(_PIO_COMPLETE=zsh_source pio)"

# Define key bindings.
z4h bindkey z4h-backward-kill-word Ctrl+Backspace Ctrl+H
z4h bindkey z4h-backward-kill-zword Ctrl+Alt+Backspace

z4h bindkey undo Ctrl+/ Shift+Tab # undo the last command line change
z4h bindkey redo Option+/         # redo the last undone command line change

z4h bindkey z4h-cd-back Shift+Left     # cd into the previous directory
z4h bindkey z4h-cd-forward Shift+Right # cd into the next directory
z4h bindkey z4h-cd-up Shift+Up         # cd into the parent directory
z4h bindkey z4h-cd-down Shift+Down     # cd into a child directory

# Autoload functions.
autoload -Uz zmv

# Define functions and completions.
function md() { [[ $# == 1 ]] && mkdir -p -- "$1" && cd -- "$1"; }
compdef _directories md

# Define named directories: ~w <=> Windows home directory on WSL.
[[ -z $z4h_win_home ]] || hash -d w="$z4h_win_home"

# Define aliases.
alias clear=z4h-clear-screen-soft-bottom

alias bash="bash --login"
alias confzsh="\$EDITOR \$ZDOTDIR"

# Set shell options: http://zsh.sourceforge.net/Doc/Release/Options.html.
setopt glob_dots    # no special treatment for file names with a leading dot
setopt no_auto_menu # require an extra TAB press to open the completion menu
setopt autocd beep extendedglob nomatch notify

# unsetopt xtrace
# exec 2>&3 3>&-

# zprof
########################################################################################################################################
